import { Box } from '@mui/material'
import EmotionButton from 'components/EmotionButton'
import StyledEmotionButton from 'components/StyledEmotion'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import About from './about'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box sx={{ display: 'flex' }}>
          <Box mr={2}>
            <Link href="./about">about</Link>
          </Box>
          <Box mr={2}>
            <Link href="./modal">modal</Link>
          </Box>
          <Box mr={2}>
            <Link href="./search">search</Link>
          </Box>
        </Box>
        <EmotionButton />
        <StyledEmotionButton />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
